=== mengxipeng1122/assembly3d/xml/schema/mesh.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://assembly.interaction3d.org/mesh" 
			xmlns="http://assembly.interaction3d.org/mesh" 
			elementFormDefault="qualified">
	
	<xs:element name="Mesh" type="mesh" />
    
	<xs:complexType name="mesh">
		<xs:sequence>
			<xs:element name="Vertices" type="vertices"/>
			<xs:element name="Triangles" type="triangles" />
			<xs:element name="Data" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="vertices">
		<xs:sequence>
			<xs:element name="Attribute" type="attribute" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="count" type="xs:positiveInteger" use="required" />
		<xs:attribute name="attributes" type="xs:positiveInteger" use="required" />
	</xs:complexType>
	
	<xs:complexType name="attribute">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="size" type="attributeSize" use="required" />
		<xs:attribute name="type" type="attributeType" use="optional" default="FLOAT"/>
	</xs:complexType>

	<xs:simpleType name="attributeSize">
		<xs:restriction base="xs:positiveInteger">
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
			<xs:enumeration value="4"/>
	    </xs:restriction>
	</xs:simpleType>
		
	<xs:simpleType name="attributeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FLOAT"/>
	    </xs:restriction>
	</xs:simpleType>
		
	<xs:complexType name="triangles">
		<xs:sequence>
			<xs:element name="Group" type="group" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" type="indexType" use="optional" default="UNSIGNED_SHORT" />		
		<xs:attribute name="groups" type="xs:positiveInteger" use="required" />
	</xs:complexType>
	
	<xs:complexType name="group">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="count" type="xs:positiveInteger" use="required" />
	</xs:complexType>
	
	<xs:simpleType name="indexType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="UNSIGNED_BYTE"/>
			<xs:enumeration value="UNSIGNED_SHORT"/>
			<xs:enumeration value="UNSIGNED_INT"/>
	    </xs:restriction>
	</xs:simpleType>		

</xs:schema>

=== mengxipeng1122/assembly3d/samples/cube/Cube.mesh.xml
<?xml version="1.0" encoding="UTF-8"?>
<Mesh xmlns="http://assembly.interaction3d.org/mesh" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://assembly.interaction3d.org/mesh http://assembly.interaction3d.org/mesh.xsd">
  <Vertices count="24" attributes="3">
    <Attribute name="POSITION" size="3" type="FLOAT"/>
    <Attribute name="NORMAL" size="3" type="FLOAT"/>
    <Attribute name="TEXCOORD" size="2" type="FLOAT"/>
  </Vertices>
  <Triangles type="UNSIGNED_BYTE" groups="6">
    <Group name="NEGATIVE_X" count="2"/>
    <Group name="POSITIVE_X" count="2"/>
    <Group name="NEGATIVE_Y" count="2"/>
    <Group name="POSITIVE_Y" count="2"/>
    <Group name="NEGATIVE_Z" count="2"/>
    <Group name="POSITIVE_Z" count="2"/>
  </Triangles>
</Mesh>
